#!/bin/bash

# script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# go to standalone-deployer root directory
cd "$DIR"/../../../ || exit

./loader/loader.app/Contents/MacOS/loader

